### ISSUE TITLE
Regarding password and ingress

### ISSUE THREAD

**Issue by Manoj-07** [reynencourt/terraform-k8s-argocd-bootstrap#6]
Hi sir
could you please let me know the command that is used to know the argocd password and could you please let me know how to deploy argocd with ingress.

**Comment by IbraheemAlSaady** [comment]
Hello @Manoj-07 

You can get the password from the terraform output with `terraform output argocd_generated_admin_password`. 

The password is stored as a secret in Kubernetes, you can also get it with `kubectl` like this: `kubectl -n argo-system get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d`

For creating an ingress, you can pass additional value files that can be used when install the ArgoCD chart

```terraform
module "argocd-bootstrap" {
  source = "kube-champ/argocd-bootstrap/k8s"
  ....

  argocd_chart_value_files = [file("${path.module"/path/to/values.yaml)]
}
```

The values.yaml file would look something like the this:

```yaml
apiVersionOverrides:
  ingress: networking.k8s.io/v1

server:
  ingress:
    enabled: true

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/host: argo.somedomain.com
      external-dns.alpha.kubernetes.io/target: nginx.somedomain.com
      ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/tls-acme: "true"
    
    ingressClassName: "nginx"

    hosts:
      - argo.somedomain.com
   
    tls:
      - hosts:
          - argo.somedomain.com
        secretName: argo-ingress-tls
```

Alternatively, you can also create an ingress resource like this

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo
  namespace: argo-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/host: argo.somedomain.com
    external-dns.alpha.kubernetes.io/target: nginx.somedomain.com
    ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: "nginx"
  rules:
  - host: argo.somedomain.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: argo-cd-argocd-server
            port:
              name: https
  tls:
    - hosts:
      - argo.somedomain.com
      secretName: argo-ingress-tls
```

Both ingress cases assume that you have Nginx ingress controller, cert-manager, and external-dns
